## Generación de paleta de colores a partir de imágenes con técnicas de machine learning no supervisado


A. Objetivo: Desarrollar un método, basado en técnicas de agrupación, que permita extraer los tonos dominantes de una imagen y generar un muestrario de los colores representativos presentes en esta. 

B. Conjunto de datos: Los datos están asociados con imágenes de obras de arte. Pueden ser descargados a partir de este enlace.

 ### Recopilación de las imágenes a partir del repositorio. La idea es seleccionar un conjunto diverso de muestras en diferentes estilos artísticos (varios pintores). Se recomienda seleccionar entre 6 y 10 imágenes.

In [2]:
import numpy as np
import os
import cv2
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans, MeanShift, estimate_bandwidth

In [3]:
def load_images(root_path, file_names, flatten=True, normalize=True):
    """
    Retorna una lista con arreglos de números. Cada arreglo representa una imagen RGB.
    
    Parametros:
    root_path : str
        Directorio raíz de las imágenes.
    file_names : list
        Lista con los nombres de los archivos de imágenes.
    flatten : bool, opcional
        Si es True, aplana las imágenes a una lista de píxeles de tres dimensiones.
    normalize : bool, opcional
        Si es True, normaliza los valores de píxeles al rango [0, 1].
    """
    image_list = list()
    for file in file_names:
        img = cv2.imread(os.path.join(root_path, file))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        if flatten:
            img = img.reshape((-1, 3))
        if normalize:
            img = img / 255.0
        image_list.append(img)
    return image_list

In [4]:
root_path = 'images'
img_files = os.listdir(root_path)
img_files

['akseli-gallen-kallela_symposium-1894.jpg',
 'hiroshige_hakone-kosuizu.jpg',
 'adolf-hitler_perchtoldsdorg-castle-and-church.jpg',
 'albrecht-altdorfer_christ-on-the-cross.jpg',
 'akseli-gallen-kallela_lemmink-inen-s-mother-1897.jpg',
 'albert-gleizes_the-schoolboy-1924.jpg',
 'antonio-ligabue_quadro.jpg',
 'abdullah-suriosubroto_indonesian-landscape-3.jpg']

In [5]:
img_original = load_images(root_path, img_files, flatten=False, normalize=False)
img_original

[array([[[ 82,  27,  59],
         [ 85,  30,  62],
         [ 90,  35,  67],
         ...,
         [ 56,  70,  71],
         [ 58,  72,  73],
         [ 58,  72,  73]],
 
        [[ 82,  27,  59],
         [ 85,  30,  62],
         [ 90,  35,  67],
         ...,
         [ 56,  70,  71],
         [ 57,  71,  72],
         [ 57,  71,  72]],
 
        [[ 86,  29,  62],
         [ 88,  31,  64],
         [ 92,  35,  68],
         ...,
         [ 54,  68,  69],
         [ 56,  70,  71],
         [ 55,  69,  70]],
 
        ...,
 
        [[218, 197, 166],
         [221, 200, 169],
         [221, 200, 169],
         ...,
         [197, 146, 127],
         [192, 141, 122],
         [191, 140, 121]],
 
        [[216, 195, 164],
         [220, 199, 168],
         [222, 201, 170],
         ...,
         [201, 150, 131],
         [197, 146, 127],
         [195, 144, 125]],
 
        [[217, 196, 165],
         [221, 200, 169],
         [223, 202, 171],
         ...,
         [204, 153, 134],
  

In [6]:
img_list = load_images(root_path, img_files, flatten=True, normalize=True)
img_list

[array([[0.32156863, 0.10588235, 0.23137255],
        [0.33333333, 0.11764706, 0.24313725],
        [0.35294118, 0.1372549 , 0.2627451 ],
        ...,
        [0.8       , 0.6       , 0.5254902 ],
        [0.78039216, 0.58039216, 0.50588235],
        [0.77647059, 0.57647059, 0.50196078]], shape=(2614233, 3)),
 array([[0.87058824, 0.79607843, 0.72941176],
        [0.85882353, 0.78431373, 0.71764706],
        [0.84313725, 0.76862745, 0.70196078],
        ...,
        [0.9372549 , 0.94117647, 0.87843137],
        [0.92156863, 0.9254902 , 0.8627451 ],
        [0.92156863, 0.9254902 , 0.8627451 ]], shape=(2866268, 3)),
 array([[0.65098039, 0.63529412, 0.52156863],
        [0.67058824, 0.65490196, 0.54117647],
        [0.71372549, 0.69803922, 0.58431373],
        ...,
        [0.72156863, 0.72941176, 0.71764706],
        [0.7254902 , 0.73333333, 0.72156863],
        [0.72941176, 0.7372549 , 0.7254902 ]], shape=(2121370, 3)),
 array([[0.48627451, 0.37254902, 0.21568627],
        [0.46666667, 